export const sampleBusinesses = [
  {
    id: "demo-1",
    name: "Westwood Cuts Studio",
    category: "beauty",
    description: "Student-friendly haircuts and styling near UCLA.",
    instagram: "https://instagram.com/westwoodcuts",
    website: null,
    phone: "310-555-0101",
    email: "hello@westwoodcuts.com",
    location: "Westwood",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-01T00:00:00.000Z",
  },
  {
    id: "demo-2",
    name: "Bruin Language Tutors",
    category: "education",
    description: "One-on-one tutoring in Spanish, Mandarin, and French.",
    instagram: "https://instagram.com/bruinlanguagetutors",
    website: "https://bruinlanguagetutors.example.com",
    phone: null,
    email: "book@bruintutors.com",
    location: "UCLA / Westwood",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-02T00:00:00.000Z",
  },
  {
    id: "demo-3",
    name: "Frame & Focus Photo",
    category: "creative",
    description: "Graduation, events, and portrait photography for students.",
    instagram: "https://instagram.com/framefocusla",
    website: null,
    phone: "424-555-0103",
    email: null,
    location: "Los Angeles",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-03T00:00:00.000Z",
  },
  {
    id: "demo-4",
    name: "Campus DJ Collective",
    category: "entertainment",
    description: "DJs available for parties, org events, and mixers.",
    instagram: "https://instagram.com/campusdjcollective",
    website: "https://campusdjcollective.example.com",
    phone: null,
    email: "bookings@campusdj.com",
    location: "West LA",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-04T00:00:00.000Z",
  },
  {
    id: "demo-5",
    name: "Bloom on Gayley",
    category: "creative",
    description: "Custom bouquets and event floral design.",
    instagram: null,
    website: "https://bloomongayley.example.com",
    phone: "310-555-0105",
    email: "orders@bloomongayley.com",
    location: "Westwood",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-05T00:00:00.000Z",
  },
  {
    id: "demo-6",
    name: "Nail Lab Westwood",
    category: "beauty",
    description: "Gel sets, nail art, and quick touch-ups for busy schedules.",
    instagram: "https://instagram.com/naillabwestwood",
    website: null,
    phone: "310-555-0106",
    email: null,
    location: "Westwood",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-06T00:00:00.000Z",
  },
  {
    id: "demo-7",
    name: "Cake Theory LA",
    category: "creative",
    description: "Custom cakes for birthdays, club events, and celebrations.",
    instagram: "https://instagram.com/caketheoryla",
    website: null,
    phone: "424-555-0107",
    email: "orders@caketheoryla.com",
    location: "Sawtelle",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-07T00:00:00.000Z",
  },
  {
    id: "demo-8",
    name: "Bruin Dev Studio",
    category: "tech",
    description: "Student web developers for portfolio and small business sites.",
    instagram: null,
    website: "https://bruindevstudio.example.com",
    phone: null,
    email: "team@bruindevstudio.com",
    location: "UCLA",
    owner_id: null,
    owner_email: null,
    created_at: "2026-02-08T00:00:00.000Z",
  },
];
